<link rel="stylesheet" href="<?php echo BASE_URL_ASSETS; ?>css/global.css" id="light-style">
<link rel="stylesheet" href="<?php echo BASE_URL_ASSETS; ?>css/global_desktop.css" id="light-style">
<link rel="stylesheet" href="<?php echo BASE_URL_ASSETS; ?>css/global_tablet.css" id="light-style">
<link rel="stylesheet" href="<?php echo BASE_URL_ASSETS; ?>css/global_mobile.css" id="light-style">
<link rel="stylesheet" href="<?php echo BASE_URL_ASSETS; ?>css/guest.css" id="light-style">
<link rel="stylesheet" href="<?php echo BASE_URL_ASSETS; ?>css/mobile.css" id="light-style">
<link rel="stylesheet" href="<?php echo BASE_URL_ASSETS; ?>css/icons.min.css" id="light-style">
<link rel="stylesheet" href="<?php echo BASE_URL_ASSETS; ?>css/app.min.css" id="light-style">
<link rel="stylesheet" href="<?php echo BASE_URL_ASSETS; ?>css/app-dark.min.css" id="dark-style">